name: Publish to GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: environment.yml
          auto-activate-base: false
      - name: Dependencies
        shell: bash
        run: |
          conda install pip
          if [ -f docs/requirements.txt ]; then pip install -r docs/requirements.txt; fi
      - name: Build
        shell: bash
        run: |
          jupyter-book build . --config docs/_config.yml --toc docs/_toc.yml
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main' && job.status == 'success'
        with:
          token: ${{ secrets.GH_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_build/html
          enable_jekyll: false
