name: Publish to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
      - name: Dependencies
        shell: bash -l {0}
        run: |
          conda install pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Build
        shell: bash -l {0}
        run: |
          jupyter-book build . --config docs/_config.yml --toc docs/_toc.yml
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main' && job.status == 'success'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_build/html
          enable_jekyll: false
